services:
  redis:
    image: redis:7-alpine
    container_name: noptrix-redis
    restart: unless-stopped

    ports:
      - "6379:6379"

    command:
      - redis-server
      - --appendonly
      - "yes"

    volumes:
      - noptrix_redis_data:/data

    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

volumes:
  noptrix_redis_data: