import Link from "next/link";
import { ArrowUpRight, CircleAlert, Clock3, PackageCheck, ShoppingBag } from "lucide-react";

export default function Page() {
    const stats = [
        { label: "Workspace status", value: "Ready", detail: "Admin API connected", tone: "mint", icon: PackageCheck },
        { label: "Your role", value: "Owner", detail: "Full workspace access", tone: "peach", icon: ShoppingBag },
        { label: "Session", value: "Active", detail: "Token refresh enabled", tone: "blue", icon: Clock3 },
    ];

    return <div className="admin-dashboard-page"><section className="admin-page-heading"><div><p className="admin-kicker">THURSDAY / SEPTEMBER 24, 2026</p><h1>Good morning, operator.</h1><p className="admin-muted">Your control room is ready. Pick a workflow to get moving.</p></div><Link href="/admin/reports" className="admin-primary-button">Open reports <ArrowUpRight size={17} /></Link></section><section className="admin-stat-grid">{stats.map(({ label, value, detail, tone, icon: Icon }) => <article className={`admin-stat-card ${tone}`} key={label}><div className="admin-stat-icon"><Icon size={19} /></div><p>{label}</p><strong>{value}</strong><span>{detail}</span></article>)}</section><section className="admin-dashboard-grid"><article className="admin-panel admin-quick-panel"><div className="admin-panel-heading"><div><p className="admin-kicker">QUICK ACCESS</p><h2>Keep the store moving</h2></div><ArrowUpRight size={19} /></div><div className="admin-quick-links"><Link href="/admin/orders"><ShoppingBag size={19} /><span>Review orders<small>See what needs attention</small></span><ArrowUpRight size={16} /></Link><Link href="/admin/inventory"><PackageCheck size={19} /><span>Check inventory<small>Keep stock levels healthy</small></span><ArrowUpRight size={16} /></Link><Link href="/admin/delivery/tracking"><Clock3 size={19} /><span>Track deliveries<small>Follow the live handoff</small></span><ArrowUpRight size={16} /></Link></div></article><article className="admin-panel admin-notice-panel"><div className="admin-notice-badge"><CircleAlert size={19} /></div><p className="admin-kicker">API NOTE</p><h2>Live metrics are next</h2><p className="admin-muted">The backend currently exposes admin auth and operational modules, but no dashboard metrics route. This panel stays honest until those endpoints are connected.</p><Link href="/admin/settings">Review settings <ArrowUpRight size={16} /></Link></article></section></div>;
}
