import type { ComponentType } from "react";
import {
    Activity,
    Award,
    BarChart3,
    Bell,
    Bike,
    Boxes,
    BriefcaseBusiness,
    Building2,
    Calculator,
    ChartNoAxesCombined,
    CircleDollarSign,
    ClipboardCheck,
    ClipboardList,
    CreditCard,
    Database,
    FileBarChart,
    FileCheck,
    FileText,
    FolderTree,
    Gauge,
    Gift,
    Globe,
    HardDrive,
    HeartHandshake,
    History,
    Inbox,
    KeyRound,
    LayoutDashboard,
    Megaphone,
    MessageCircle,
    Package,
    PackageCheck,
    PanelTop,
    Percent,
    Radio,
    Receipt,
    RefreshCcw,
    RotateCcw,
    Search,
    Send,
    Server,
    Settings,
    ShieldCheck,
    ShoppingBag,
    ShoppingCart,
    SlidersHorizontal,
    Smartphone,
    Star,
    Store,
    Tags,
    TicketPercent,
    Truck,
    UserPlus,
    Users,
    Wallet,
    Webhook,
    Wrench,
    Zap,
} from "lucide-react";

export interface AdminNavigationItem {
    readonly id: string;
    readonly label: string;
    readonly href: string;
    readonly icon: ComponentType<{
        size?: number;
        strokeWidth?: number;
    }>;
    readonly permission?: string;
    readonly ownerOnly?: boolean;
    readonly badgeKey?: string;
}

export interface AdminNavigationSection {
    readonly id: string;
    readonly label: string;
    readonly icon: ComponentType<{
        size?: number;
        strokeWidth?: number;
    }>;
    readonly items: readonly AdminNavigationItem[];
    readonly ownerOnly?: boolean;
}

export const ADMIN_NAVIGATION_SECTIONS: readonly AdminNavigationSection[] = [
    {
        id: "command-center",
        label: "Command Center",
        icon: Gauge,
        items: [
            {
                id: "dashboard",
                label: "Dashboard",
                href: "/admin",
                icon: LayoutDashboard,
            },
            {
                id: "global-search",
                label: "Global Search",
                href: "/admin/search",
                icon: Search,
            },
            {
                id: "quick-actions",
                label: "Quick Actions",
                href: "/admin/quick-actions",
                icon: Zap,
            },
            {
                id: "favorites",
                label: "Favorites",
                href: "/admin/favorites",
                icon: Star,
            },
            {
                id: "recently-visited",
                label: "Recently Visited",
                href: "/admin/recent",
                icon: History,
            },
            {
                id: "tasks",
                label: "Tasks",
                href: "/admin/tasks",
                icon: ClipboardCheck,
            },
            {
                id: "smart-insights",
                label: "Smart Insights",
                href: "/admin/insights",
                icon: ChartNoAxesCombined,
            },
        ],
    },

    {
        id: "live-operations",
        label: "Live Operations",
        icon: Radio,
        items: [
            {
                id: "live-orders",
                label: "Live Orders",
                href: "/admin/live/orders",
                icon: ShoppingCart,
                badgeKey: "liveOrders",
            },
            {
                id: "live-deliveries",
                label: "Live Deliveries",
                href: "/admin/live/deliveries",
                icon: Truck,
                badgeKey: "liveDeliveries",
            },
            {
                id: "live-payments",
                label: "Live Payments",
                href: "/admin/live/payments",
                icon: CreditCard,
            },
            {
                id: "live-customers",
                label: "Live Customers",
                href: "/admin/live/customers",
                icon: Users,
            },
            {
                id: "live-sellers",
                label: "Live Sellers",
                href: "/admin/live/sellers",
                icon: Store,
            },
            {
                id: "live-riders",
                label: "Live Riders",
                href: "/admin/live/riders",
                icon: Bike,
            },
            {
                id: "system-events",
                label: "System Events",
                href: "/admin/live/events",
                icon: Activity,
            },
        ],
    },

    {
        id: "communication",
        label: "Communication Hub",
        icon: MessageCircle,
        items: [
            {
                id: "inbox",
                label: "Inbox",
                href: "/admin/communication/inbox",
                icon: Inbox,
                badgeKey: "unreadMessages",
            },
            {
                id: "customer-conversations",
                label: "Customers",
                href: "/admin/communication/inbox/customers",
                icon: Users,
            },
            {
                id: "seller-conversations",
                label: "Sellers",
                href: "/admin/communication/inbox/sellers",
                icon: Store,
            },
            {
                id: "rider-conversations",
                label: "Riders",
                href: "/admin/communication/inbox/riders",
                icon: Bike,
            },
            {
                id: "employee-conversations",
                label: "Employees",
                href: "/admin/communication/inbox/employees",
                icon: BriefcaseBusiness,
            },
            {
                id: "notifications",
                label: "Notifications",
                href: "/admin/communication/notifications",
                icon: Bell,
                badgeKey: "unreadNotifications",
            },
            {
                id: "announcements",
                label: "Announcements",
                href: "/admin/communication/announcements",
                icon: Megaphone,
                badgeKey: "announcements",
            },
            {
                id: "broadcast",
                label: "Broadcast",
                href: "/admin/communication/broadcast",
                icon: Send,
            },
            {
                id: "communication-templates",
                label: "Templates",
                href: "/admin/communication/templates",
                icon: FileText,
            },
        ],
    },

    {
        id: "people",
        label: "People",
        icon: Users,
        items: [
            {
                id: "users",
                label: "Users",
                href: "/admin/users",
                icon: Users,
            },
            {
                id: "customers",
                label: "Customers",
                href: "/admin/customers",
                icon: UserPlus,
            },
            {
                id: "customer-groups",
                label: "Customer Groups",
                href: "/admin/customers/groups",
                icon: Tags,
            },
            {
                id: "customer-addresses",
                label: "Customer Addresses",
                href: "/admin/customers/addresses",
                icon: Globe,
            },
            {
                id: "customer-activity",
                label: "Customer Activity",
                href: "/admin/customers/activity",
                icon: Activity,
            },
            {
                id: "customer-sessions",
                label: "Customer Sessions",
                href: "/admin/customers/sessions",
                icon: Smartphone,
            },
            {
                id: "customer-notification-preferences",
                label: "Notification Preferences",
                href: "/admin/customers/notification-preferences",
                icon: Bell,
            },
        ],
    },

    {
        id: "administration",
        label: "Administration",
        icon: Building2,
        ownerOnly: true,
        items: [
            {
                id: "admins",
                label: "Admins",
                href: "/admin/admins",
                icon: ShieldCheck,
                ownerOnly: true,
            },
            {
                id: "admin-invitations",
                label: "Admin Invitations",
                href: "/admin/invitations",
                icon: UserPlus,
                ownerOnly: true,
            },
            {
                id: "roles",
                label: "Roles",
                href: "/owner/roles",
                icon: KeyRound,
                ownerOnly: true,
            },
            {
                id: "permissions",
                label: "Permissions",
                href: "/owner/permissions",
                icon: ShieldCheck,
                ownerOnly: true,
            },
            {
                id: "role-permissions",
                label: "Role Permissions",
                href: "/admin/role-permissions",
                icon: SlidersHorizontal,
                ownerOnly: true,
            },
            {
                id: "employees",
                label: "Employees",
                href: "/admin/employees",
                icon: BriefcaseBusiness,
                ownerOnly: true,
            },
            {
                id: "employee-invitations",
                label: "Employee Invitations",
                href: "/admin/employee-invitations",
                icon: UserPlus,
                ownerOnly: true,
            },
            {
                id: "admin-sessions",
                label: "Sessions",
                href: "/admin/admin-sessions",
                icon: Smartphone,
                ownerOnly: true,
            },
            {
                id: "admin-activity",
                label: "Admin Activity",
                href: "/admin/admin-activity",
                icon: Activity,
                ownerOnly: true,
            },
            {
                id: "audit-logs",
                label: "Audit Logs",
                href: "/admin/audit-logs",
                icon: History,
                ownerOnly: true,
            },
        ],
    },

    {
        id: "seller-management",
        label: "Seller Management",
        icon: Store,
        items: [
            {
                id: "sellers",
                label: "Sellers",
                href: "/admin/sellers",
                icon: Store,
                permission: "sellers.read",
            },
            {
                id: "seller-applications",
                label: "Seller Applications",
                href: "/admin/seller-applications",
                icon: FileCheck,
                permission: "seller_applications.read",
                badgeKey: "sellerApplications",
            },
            {
                id: "seller-verification",
                label: "Seller Verification",
                href: "/admin/sellers/verification",
                icon: ShieldCheck,
                permission: "sellers.verify",
            },
            {
                id: "seller-products",
                label: "Seller Products",
                href: "/admin/seller-products",
                icon: Package,
                permission: "seller_products.read",
            },
            {
                id: "seller-orders",
                label: "Seller Orders",
                href: "/admin/seller-orders",
                icon: ShoppingCart,
                permission: "seller_orders.read",
            },
            {
                id: "seller-reviews",
                label: "Seller Reviews",
                href: "/admin/sellers/reviews",
                icon: Star,
                permission: "seller_reviews.read",
            },
            {
                id: "seller-messages",
                label: "Seller Messages",
                href: "/admin/communication/inbox/sellers",
                icon: MessageCircle,
            },
            {
                id: "seller-payouts",
                label: "Seller Payouts",
                href: "/admin/sellers/payouts",
                icon: Wallet,
                permission: "seller_payouts.read",
            },
            {
                id: "seller-performance",
                label: "Seller Performance",
                href: "/admin/sellers/performance",
                icon: BarChart3,
                permission: "sellers.read",
            },
            {
                id: "seller-suspensions",
                label: "Seller Suspensions",
                href: "/admin/sellers/suspensions",
                icon: ShieldCheck,
                permission: "sellers.suspend",
            },
        ],
    },

    {
        id: "rider-management",
        label: "Rider Management",
        icon: Bike,
        items: [
            {
                id: "riders",
                label: "Riders",
                href: "/admin/riders",
                icon: Bike,
                permission: "riders.read",
            },
            {
                id: "rider-applications",
                label: "Rider Applications",
                href: "/admin/rider-applications",
                icon: FileCheck,
                permission: "rider_applications.read",
                badgeKey: "riderApplications",
            },
            {
                id: "rider-verification",
                label: "Rider Verification",
                href: "/admin/riders/verification",
                icon: ShieldCheck,
                permission: "riders.verify",
            },
            {
                id: "rider-status",
                label: "Rider Status",
                href: "/admin/riders/status",
                icon: Activity,
                permission: "riders.read",
            },
            {
                id: "rider-earnings",
                label: "Rider Earnings",
                href: "/admin/rider-earnings",
                icon: Wallet,
                permission: "rider_earnings.read",
            },
            {
                id: "rider-payouts",
                label: "Rider Payouts",
                href: "/admin/riders/payouts",
                icon: CircleDollarSign,
                permission: "rider_payouts.read",
            },
            {
                id: "delivery-assignments",
                label: "Delivery Assignments",
                href: "/admin/delivery/assignments",
                icon: ClipboardList,
                permission: "delivery.read",
            },
            {
                id: "rider-tracking",
                label: "Rider Tracking",
                href: "/admin/tracking",
                icon: Globe,
                permission: "tracking.read",
            },
            {
                id: "rider-messages",
                label: "Rider Messages",
                href: "/admin/communication/inbox/riders",
                icon: MessageCircle,
            },
            {
                id: "rider-performance",
                label: "Rider Performance",
                href: "/admin/riders/performance",
                icon: BarChart3,
                permission: "riders.read",
            },
        ],
    },

    {
        id: "catalog",
        label: "Catalog Management",
        icon: Package,
        items: [
            {
                id: "products",
                label: "Products",
                href: "/admin/products",
                icon: Package,
                permission: "products.read",
            },
            {
                id: "categories",
                label: "Categories",
                href: "/admin/categories",
                icon: FolderTree,
                permission: "categories.read",
            },
            {
                id: "subcategories",
                label: "Subcategories",
                href: "/admin/subcategories",
                icon: FolderTree,
                permission: "subcategories.read",
            },
            {
                id: "brands",
                label: "Brands",
                href: "/admin/brands",
                icon: Tags,
                permission: "brands.read",
            },
            {
                id: "collections",
                label: "Collections",
                href: "/admin/collections",
                icon: Boxes,
                permission: "collections.read",
            },
            {
                id: "attributes",
                label: "Attributes",
                href: "/admin/attributes",
                icon: SlidersHorizontal,
                permission: "attributes.read",
            },
            {
                id: "product-variants",
                label: "Product Variants",
                href: "/admin/product-variants",
                icon: Boxes,
                permission: "product_variants.read",
            },
            {
                id: "product-images",
                label: "Product Images",
                href: "/admin/product-images",
                icon: PanelTop,
                permission: "product_images.read",
            },
            {
                id: "product-tags",
                label: "Product Tags",
                href: "/admin/product-tags",
                icon: Tags,
                permission: "product_tags.read",
            },
            {
                id: "reviews",
                label: "Reviews",
                href: "/admin/reviews",
                icon: Star,
                permission: "reviews.read",
            },
            {
                id: "ratings",
                label: "Ratings",
                href: "/admin/ratings",
                icon: Star,
                permission: "ratings.read",
            },
            {
                id: "questions",
                label: "Questions",
                href: "/admin/questions",
                icon: MessageCircle,
                permission: "questions.read",
            },
            {
                id: "low-stock",
                label: "Low Stock",
                href: "/admin/low-stock",
                icon: PackageCheck,
                permission: "inventory.read",
                badgeKey: "lowStock",
            },
        ],
    },

    {
        id: "orders-sales",
        label: "Orders & Sales",
        icon: ShoppingCart,
        items: [
            {
                id: "orders",
                label: "Orders",
                href: "/admin/orders",
                icon: ShoppingCart,
                permission: "orders.read",
                badgeKey: "orders",
            },
            {
                id: "abandoned-carts",
                label: "Abandoned Carts",
                href: "/admin/abandoned-carts",
                icon: ShoppingBag,
                permission: "abandoned_carts.read",
            },
            {
                id: "checkout",
                label: "Checkout",
                href: "/admin/checkout",
                icon: CreditCard,
                permission: "checkout.read",
            },
            {
                id: "cancellations",
                label: "Cancellations",
                href: "/admin/cancellations",
                icon: RotateCcw,
                permission: "cancellations.read",
            },
            {
                id: "returns",
                label: "Returns",
                href: "/admin/returns",
                icon: RefreshCcw,
                permission: "returns.read",
            },
            {
                id: "refunds",
                label: "Refunds",
                href: "/admin/refunds",
                icon: RotateCcw,
                permission: "refunds.read",
                badgeKey: "refunds",
            },
            {
                id: "invoices",
                label: "Invoices",
                href: "/admin/invoices",
                icon: FileText,
                permission: "invoices.read",
            },
            {
                id: "receipts",
                label: "Receipts",
                href: "/admin/receipts",
                icon: Receipt,
                permission: "receipts.read",
            },
            {
                id: "order-activity",
                label: "Order Activity",
                href: "/admin/orders/activity",
                icon: Activity,
                permission: "orders.read",
            },
        ],
    },

    {
        id: "marketing",
        label: "Marketing",
        icon: Megaphone,
        items: [
            {
                id: "banners",
                label: "Banners",
                href: "/admin/banners",
                icon: PanelTop,
                permission: "banners.read",
            },
            {
                id: "campaigns",
                label: "Campaigns",
                href: "/admin/campaigns",
                icon: Megaphone,
                permission: "campaigns.read",
            },
            {
                id: "email-campaigns",
                label: "Email Campaigns",
                href: "/admin/email-campaigns",
                icon: FileText,
                permission: "email_campaigns.read",
            },
            {
                id: "sms-campaigns",
                label: "SMS Campaigns",
                href: "/admin/sms-campaigns",
                icon: Smartphone,
                permission: "sms_campaigns.read",
            },
            {
                id: "push-campaigns",
                label: "Push Campaigns",
                href: "/admin/push-campaigns",
                icon: Bell,
                permission: "push_campaigns.read",
            },
            {
                id: "coupons",
                label: "Coupons",
                href: "/admin/coupons",
                icon: TicketPercent,
                permission: "coupons.read",
            },
            {
                id: "discounts",
                label: "Discounts",
                href: "/admin/discounts",
                icon: Percent,
                permission: "discounts.read",
            },
            {
                id: "promotions",
                label: "Promotions",
                href: "/admin/promotions",
                icon: Gift,
                permission: "promotions.read",
            },
            {
                id: "flash-sales",
                label: "Flash Sales",
                href: "/admin/flash-sales",
                icon: Zap,
                permission: "flash_sales.read",
            },
            {
                id: "gift-cards",
                label: "Gift Cards",
                href: "/admin/gift-cards",
                icon: Gift,
                permission: "gift_cards.read",
            },
            {
                id: "marketing-analytics",
                label: "Marketing Analytics",
                href: "/admin/marketing/analytics",
                icon: BarChart3,
                permission: "marketing.read",
            },
        ],
    },

    {
        id: "inventory-procurement",
        label: "Inventory & Procurement",
        icon: Boxes,
        items: [
            {
                id: "inventory",
                label: "Inventory",
                href: "/admin/inventory",
                icon: Boxes,
                permission: "inventory.read",
            },
            {
                id: "stock-movements",
                label: "Stock Movements",
                href: "/admin/stock-movements",
                icon: Activity,
                permission: "stock_movements.read",
            },
            {
                id: "stock-transfers",
                label: "Stock Transfers",
                href: "/admin/stock-transfers",
                icon: RefreshCcw,
                permission: "stock_transfers.read",
            },
            {
                id: "inventory-low-stock",
                label: "Low Stock",
                href: "/admin/low-stock",
                icon: PackageCheck,
                permission: "inventory.read",
            },
            {
                id: "purchases",
                label: "Purchases",
                href: "/admin/purchases",
                icon: ShoppingBag,
                permission: "purchases.read",
            },
            {
                id: "purchase-returns",
                label: "Purchase Returns",
                href: "/admin/purchase-returns",
                icon: RotateCcw,
                permission: "purchase_returns.read",
            },
            {
                id: "suppliers",
                label: "Suppliers",
                href: "/admin/suppliers",
                icon: Store,
                permission: "suppliers.read",
            },
            {
                id: "inventory-reports",
                label: "Inventory Reports",
                href: "/admin/reports/inventory",
                icon: FileBarChart,
                permission: "inventory_reports.read",
            },
        ],
    },

    {
        id: "payments-payouts",
        label: "Payments & Payouts",
        icon: CreditCard,
        items: [
            {
                id: "payments",
                label: "Payments",
                href: "/admin/payments",
                icon: CreditCard,
                permission: "payments.read",
            },
            {
                id: "transactions",
                label: "Transactions",
                href: "/admin/payments/transactions",
                icon: Receipt,
                permission: "transactions.read",
            },
            {
                id: "payment-methods",
                label: "Payment Methods",
                href: "/admin/payment-methods",
                icon: Wallet,
                permission: "payment_methods.read",
            },
            {
                id: "cod",
                label: "COD",
                href: "/admin/cod",
                icon: CircleDollarSign,
                permission: "cod.read",
            },
            {
                id: "payment-failures",
                label: "Payment Failures",
                href: "/admin/payments/failures",
                icon: Activity,
                permission: "payments.read",
            },
            {
                id: "payment-refunds",
                label: "Refunds",
                href: "/admin/refunds",
                icon: RotateCcw,
                permission: "refunds.read",
            },
            {
                id: "payment-seller-payouts",
                label: "Seller Payouts",
                href: "/admin/sellers/payouts",
                icon: Wallet,
                permission: "seller_payouts.read",
            },
            {
                id: "payment-rider-payouts",
                label: "Rider Payouts",
                href: "/admin/riders/payouts",
                icon: Wallet,
                permission: "rider_payouts.read",
            },
            {
                id: "payment-reports",
                label: "Payment Reports",
                href: "/admin/reports/payments",
                icon: FileBarChart,
                permission: "payment_reports.read",
            },
        ],
    },

    {
        id: "accounting",
        label: "Accounting",
        icon: Calculator,
        items: [
            {
                id: "accounting-dashboard",
                label: "Dashboard",
                href: "/admin/accounting",
                icon: LayoutDashboard,
                permission: "accounting.read",
            },
            {
                id: "chart-of-accounts",
                label: "Chart of Accounts",
                href: "/admin/accounting/chart-of-accounts",
                icon: FolderTree,
                permission: "accounting.read",
            },
            {
                id: "accounts",
                label: "Accounts",
                href: "/admin/accounting/accounts",
                icon: Wallet,
                permission: "accounting.read",
            },
            {
                id: "journal",
                label: "Journal",
                href: "/admin/accounting/journal",
                icon: FileText,
                permission: "accounting.read",
            },
            {
                id: "ledger",
                label: "Ledger",
                href: "/admin/accounting/ledger",
                icon: Receipt,
                permission: "accounting.read",
            },
            {
                id: "assets",
                label: "Assets",
                href: "/admin/accounting/assets",
                icon: Boxes,
                permission: "accounting.read",
            },
            {
                id: "liabilities",
                label: "Liabilities",
                href: "/admin/accounting/liabilities",
                icon: Wallet,
                permission: "accounting.read",
            },
            {
                id: "income",
                label: "Income",
                href: "/admin/accounting/income",
                icon: CircleDollarSign,
                permission: "accounting.read",
            },
            {
                id: "expenses",
                label: "Expenses",
                href: "/admin/accounting/expenses",
                icon: CircleDollarSign,
                permission: "accounting.read",
            },
            {
                id: "cash-flow",
                label: "Cash Flow",
                href: "/admin/accounting/cash-flow",
                icon: BarChart3,
                permission: "accounting.read",
            },
            {
                id: "balance-sheet",
                label: "Balance Sheet",
                href: "/admin/accounting/balance-sheet",
                icon: FileBarChart,
                permission: "accounting.read",
            },
            {
                id: "profit-loss",
                label: "Profit & Loss",
                href: "/admin/accounting/profit-loss",
                icon: ChartNoAxesCombined,
                permission: "accounting.read",
            },
            {
                id: "accounting-reports",
                label: "Accounting Reports",
                href: "/admin/reports/accounting",
                icon: FileBarChart,
                permission: "accounting_reports.read",
            },
        ],
    },

    {
        id: "delivery-shipping",
        label: "Delivery & Shipping",
        icon: Truck,
        items: [
            {
                id: "delivery",
                label: "Delivery",
                href: "/admin/delivery",
                icon: Truck,
                permission: "delivery.read",
            },
            {
                id: "delivery-assignment",
                label: "Delivery Assignments",
                href: "/admin/delivery/assignments",
                icon: ClipboardList,
                permission: "delivery.read",
            },
            {
                id: "delivery-zones",
                label: "Delivery Zones",
                href: "/admin/delivery-zones",
                icon: Globe,
                permission: "delivery_zones.read",
            },
            {
                id: "delivery-fees",
                label: "Delivery Fees",
                href: "/admin/delivery-fees",
                icon: CircleDollarSign,
                permission: "delivery_fees.read",
            },
            {
                id: "shipping",
                label: "Shipping",
                href: "/admin/shipping",
                icon: Truck,
                permission: "shipping.read",
            },
            {
                id: "shipping-providers",
                label: "Shipping Providers",
                href: "/admin/shipping/providers",
                icon: Store,
                permission: "shipping.read",
            },
            {
                id: "delivery-tracking",
                label: "Delivery Tracking",
                href: "/admin/tracking",
                icon: Globe,
                permission: "tracking.read",
            },
            {
                id: "delivery-reports",
                label: "Delivery Reports",
                href: "/admin/reports/delivery",
                icon: FileBarChart,
                permission: "delivery_reports.read",
            },
        ],
    },

    {
        id: "customer-programs",
        label: "Customer Programs",
        icon: HeartHandshake,
        items: [
            {
                id: "loyalty",
                label: "Loyalty",
                href: "/admin/loyalty",
                icon: HeartHandshake,
                permission: "loyalty.read",
            },
            {
                id: "reward-points",
                label: "Reward Points",
                href: "/admin/reward-points",
                icon: Gift,
                permission: "reward_points.read",
            },
            {
                id: "referrals",
                label: "Referrals",
                href: "/admin/referrals",
                icon: Users,
                permission: "referrals.read",
            },
            {
                id: "program-gift-cards",
                label: "Gift Cards",
                href: "/admin/gift-cards",
                icon: Gift,
                permission: "gift_cards.read",
            },
            {
                id: "customer-rewards",
                label: "Customer Rewards",
                href: "/admin/customer-programs/rewards",
                icon: Award,
                permission: "rewards.read",
            },
            {
                id: "program-analytics",
                label: "Program Analytics",
                href: "/admin/customer-programs/analytics",
                icon: BarChart3,
                permission: "loyalty.read",
            },
        ],
    },

    {
        id: "hr-recruitment",
        label: "HR & Recruitment",
        icon: BriefcaseBusiness,
        items: [
            {
                id: "job-vacancies",
                label: "Job Vacancies",
                href: "/admin/job-vacancies",
                icon: ClipboardList,
                permission: "job_vacancies.read",
            },
            {
                id: "job-applications",
                label: "Job Applications",
                href: "/admin/job-applications",
                icon: FileCheck,
                permission: "job_applications.read",
            },
            {
                id: "hr-employees",
                label: "Employees",
                href: "/admin/employees",
                icon: Users,
                permission: "employees.read",
            },
            {
                id: "hr-employee-invitations",
                label: "Employee Invitations",
                href: "/admin/employee-invitations",
                icon: UserPlus,
                permission: "employee_invitations.read",
            },
            {
                id: "employee-activity",
                label: "Employee Activity",
                href: "/admin/employees/activity",
                icon: Activity,
                permission: "employees.read",
            },
            {
                id: "recruitment-reports",
                label: "Recruitment Reports",
                href: "/admin/reports/recruitment",
                icon: FileBarChart,
                permission: "recruitment_reports.read",
            },
        ],
    },

    {
        id: "reports-bi",
        label: "Reports & Business Intelligence",
        icon: BarChart3,
        items: [
            {
                id: "sales-analytics",
                label: "Sales Analytics",
                href: "/admin/reports/sales",
                icon: BarChart3,
                permission: "reports.sales.read",
            },
            {
                id: "order-analytics",
                label: "Order Analytics",
                href: "/admin/reports/orders",
                icon: ChartNoAxesCombined,
                permission: "reports.orders.read",
            },
            {
                id: "customer-analytics",
                label: "Customer Analytics",
                href: "/admin/reports/customers",
                icon: Users,
                permission: "reports.customers.read",
            },
            {
                id: "product-analytics",
                label: "Product Analytics",
                href: "/admin/reports/products",
                icon: Package,
                permission: "reports.products.read",
            },
            {
                id: "seller-analytics",
                label: "Seller Analytics",
                href: "/admin/reports/sellers",
                icon: Store,
                permission: "reports.sellers.read",
            },
            {
                id: "rider-analytics",
                label: "Rider Analytics",
                href: "/admin/reports/riders",
                icon: Bike,
                permission: "reports.riders.read",
            },
            {
                id: "inventory-analytics",
                label: "Inventory Analytics",
                href: "/admin/reports/inventory",
                icon: Boxes,
                permission: "reports.inventory.read",
            },
            {
                id: "payment-analytics",
                label: "Payment Analytics",
                href: "/admin/reports/payments",
                icon: CreditCard,
                permission: "reports.payments.read",
            },
            {
                id: "marketing-analytics-reports",
                label: "Marketing Analytics",
                href: "/admin/reports/marketing",
                icon: Megaphone,
                permission: "reports.marketing.read",
            },
            {
                id: "delivery-analytics",
                label: "Delivery Analytics",
                href: "/admin/reports/delivery",
                icon: Truck,
                permission: "reports.delivery.read",
            },
            {
                id: "notification-analytics",
                label: "Notification Analytics",
                href: "/admin/reports/notifications",
                icon: Bell,
                permission: "reports.notifications.read",
            },
            {
                id: "cohort-analytics",
                label: "Cohort Analytics",
                href: "/admin/reports/cohorts",
                icon: Users,
                permission: "reports.analytics.read",
            },
            {
                id: "funnel-analytics",
                label: "Funnel Analytics",
                href: "/admin/reports/funnel",
                icon: ChartNoAxesCombined,
                permission: "reports.analytics.read",
            },
            {
                id: "revenue-analytics",
                label: "Revenue Analytics",
                href: "/admin/reports/revenue",
                icon: CircleDollarSign,
                permission: "reports.analytics.read",
            },
            {
                id: "export-center",
                label: "Export Center",
                href: "/admin/reports/exports",
                icon: FileBarChart,
                permission: "reports.export",
            },
        ],
    },

    {
        id: "workflow-automation",
        label: "Workflow Automation",
        icon: Zap,
        items: [
            {
                id: "automation-rules",
                label: "Automation Rules",
                href: "/admin/automation",
                icon: Zap,
                ownerOnly: true,
            },
            {
                id: "order-rules",
                label: "Order Rules",
                href: "/admin/automation/orders",
                icon: ShoppingCart,
                ownerOnly: true,
            },
            {
                id: "notification-rules",
                label: "Notification Rules",
                href: "/admin/automation/notifications",
                icon: Bell,
                ownerOnly: true,
            },
            {
                id: "refund-rules",
                label: "Refund Rules",
                href: "/admin/automation/refunds",
                icon: RotateCcw,
                ownerOnly: true,
            },
            {
                id: "seller-rules",
                label: "Seller Rules",
                href: "/admin/automation/sellers",
                icon: Store,
                ownerOnly: true,
            },
            {
                id: "delivery-rules",
                label: "Delivery Rules",
                href: "/admin/automation/delivery",
                icon: Truck,
                ownerOnly: true,
            },
            {
                id: "scheduled-tasks",
                label: "Scheduled Tasks",
                href: "/admin/automation/scheduled",
                icon: ClipboardList,
                ownerOnly: true,
            },
            {
                id: "automation-logs",
                label: "Automation Logs",
                href: "/admin/automation/logs",
                icon: History,
                ownerOnly: true,
            },
        ],
    },

    {
        id: "security-center",
        label: "Security Center",
        icon: ShieldCheck,
        ownerOnly: true,
        items: [
            {
                id: "active-sessions",
                label: "Active Sessions",
                href: "/admin/security/sessions",
                icon: Smartphone,
                ownerOnly: true,
            },
            {
                id: "login-history",
                label: "Login History",
                href: "/admin/security/login-history",
                icon: History,
                ownerOnly: true,
            },
            {
                id: "security-events",
                label: "Security Events",
                href: "/admin/security/events",
                icon: ShieldCheck,
                ownerOnly: true,
            },
            {
                id: "suspicious-activity",
                label: "Suspicious Activity",
                href: "/admin/security/suspicious",
                icon: Activity,
                ownerOnly: true,
            },
            {
                id: "permission-changes",
                label: "Permission Changes",
                href: "/admin/security/permissions",
                icon: KeyRound,
                ownerOnly: true,
            },
            {
                id: "security-admin-activity",
                label: "Admin Activity",
                href: "/admin/security/admin-activity",
                icon: Activity,
                ownerOnly: true,
            },
            {
                id: "security-audit-logs",
                label: "Audit Logs",
                href: "/admin/security/audit-logs",
                icon: History,
                ownerOnly: true,
            },
            {
                id: "security-alerts",
                label: "Security Alerts",
                href: "/admin/security/alerts",
                icon: Bell,
                ownerOnly: true,
            },
        ],
    },

    {
        id: "system-monitoring",
        label: "System Monitoring",
        icon: Server,
        ownerOnly: true,
        items: [
            {
                id: "system-health",
                label: "System Health",
                href: "/admin/system/health",
                icon: Gauge,
                ownerOnly: true,
            },
            {
                id: "api-health",
                label: "API Health",
                href: "/admin/system/api",
                icon: Activity,
                ownerOnly: true,
            },
            {
                id: "database-status",
                label: "Database Status",
                href: "/admin/system/database",
                icon: Database,
                ownerOnly: true,
            },
            {
                id: "redis-status",
                label: "Redis Status",
                href: "/admin/system/redis",
                icon: Server,
                ownerOnly: true,
            },
            {
                id: "queue-monitoring",
                label: "Queue Monitoring",
                href: "/admin/system/queues",
                icon: Activity,
                ownerOnly: true,
            },
            {
                id: "worker-monitoring",
                label: "Worker Monitoring",
                href: "/admin/system/workers",
                icon: Server,
                ownerOnly: true,
            },
            {
                id: "email-delivery",
                label: "Email Delivery",
                href: "/admin/system/email",
                icon: FileText,
                ownerOnly: true,
            },
            {
                id: "sms-delivery",
                label: "SMS Delivery",
                href: "/admin/system/sms",
                icon: Smartphone,
                ownerOnly: true,
            },
            {
                id: "push-delivery",
                label: "Push Delivery",
                href: "/admin/system/push",
                icon: Bell,
                ownerOnly: true,
            },
            {
                id: "socket-connections",
                label: "Socket Connections",
                href: "/admin/system/sockets",
                icon: Activity,
                ownerOnly: true,
            },
            {
                id: "error-monitoring",
                label: "Error Monitoring",
                href: "/admin/system/errors",
                icon: Activity,
                ownerOnly: true,
            },
            {
                id: "system-diagnostics",
                label: "System Diagnostics",
                href: "/admin/system/diagnostics",
                icon: Wrench,
                ownerOnly: true,
            },
        ],
    },

    {
        id: "developer-operations",
        label: "Developer & Operations",
        icon: Wrench,
        ownerOnly: true,
        items: [
            {
                id: "api-logs",
                label: "API Logs",
                href: "/admin/operations/api-logs",
                icon: FileText,
                ownerOnly: true,
            },
            {
                id: "event-logs",
                label: "Event Logs",
                href: "/admin/operations/events",
                icon: Activity,
                ownerOnly: true,
            },
            {
                id: "webhooks",
                label: "Webhooks",
                href: "/admin/operations/webhooks",
                icon: Webhook,
                ownerOnly: true,
            },
            {
                id: "queue-jobs",
                label: "Queue Jobs",
                href: "/admin/operations/queues",
                icon: ClipboardList,
                ownerOnly: true,
            },
            {
                id: "failed-jobs",
                label: "Failed Jobs",
                href: "/admin/operations/failed-jobs",
                icon: Activity,
                ownerOnly: true,
            },
            {
                id: "export-jobs",
                label: "Export Jobs",
                href: "/admin/operations/export-jobs",
                icon: FileBarChart,
                ownerOnly: true,
            },
            {
                id: "integration-status",
                label: "Integration Status",
                href: "/admin/operations/integrations",
                icon: Globe,
                ownerOnly: true,
            },
            {
                id: "diagnostics",
                label: "Diagnostics",
                href: "/admin/operations/diagnostics",
                icon: Wrench,
                ownerOnly: true,
            },
        ],
    },

    {
        id: "system-settings",
        label: "System Settings",
        icon: Settings,
        ownerOnly: true,
        items: [
            {
                id: "general-settings",
                label: "General",
                href: "/admin/settings/general",
                icon: Settings,
                ownerOnly: true,
            },
            {
                id: "business-settings",
                label: "Business",
                href: "/admin/settings/business",
                icon: Building2,
                ownerOnly: true,
            },
            {
                id: "security-settings",
                label: "Security",
                href: "/admin/settings/security",
                icon: ShieldCheck,
                ownerOnly: true,
            },
            {
                id: "currency-settings",
                label: "Currency",
                href: "/admin/settings/currency",
                icon: CircleDollarSign,
                ownerOnly: true,
            },
            {
                id: "tax-settings",
                label: "Tax",
                href: "/admin/settings/tax",
                icon: Calculator,
                ownerOnly: true,
            },
            {
                id: "payment-settings",
                label: "Payment",
                href: "/admin/settings/payment",
                icon: CreditCard,
                ownerOnly: true,
            },
            {
                id: "shipping-settings",
                label: "Shipping",
                href: "/admin/settings/shipping",
                icon: Truck,
                ownerOnly: true,
            },
            {
                id: "email-settings",
                label: "Email",
                href: "/admin/settings/email",
                icon: FileText,
                ownerOnly: true,
            },
            {
                id: "sms-settings",
                label: "SMS",
                href: "/admin/settings/sms",
                icon: Smartphone,
                ownerOnly: true,
            },
            {
                id: "push-settings",
                label: "Push",
                href: "/admin/settings/push",
                icon: Bell,
                ownerOnly: true,
            },
            {
                id: "notification-settings",
                label: "Notifications",
                href: "/admin/settings/notifications",
                icon: Bell,
                ownerOnly: true,
            },
            {
                id: "media-settings",
                label: "Media / Cloudinary",
                href: "/admin/settings/media",
                icon: HardDrive,
                ownerOnly: true,
            },
            {
                id: "localization-settings",
                label: "Localization",
                href: "/admin/settings/localization",
                icon: Globe,
                ownerOnly: true,
            },
            {
                id: "feature-flags",
                label: "Feature Flags",
                href: "/admin/settings/features",
                icon: SlidersHorizontal,
                ownerOnly: true,
            },
        ],
    },
];

export const ADMIN_DASHBOARD_PATH = "/admin";
